on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run bundle
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: dist/get-200-status-test.js
